### ISSUE TITLE
Some menuseparators are double tickness when using display scaling.

### ISSUE THREAD

**Issue by Claymont** [M1ch431/FirefoxW10ContextMenus#1]
When using Windows display scaling some menuseparators are too thick.

Below image is taken at 150% display scaling. *I see this at 125% as well.*

![context](https://user-images.githubusercontent.com/28518684/67634541-c9396500-f8bd-11e9-8f81-81a6ca193d6a.png)

With 100% display scaling the menus render correctly.

Firefox: 70.0 64-bit & Nightly 64-Bit
OS: Windows 10 64-bit 1903 18362.418
Resolution: 1920x1080p (native)

**Comment by M1ch431** [comment]
This should be fixed now, could you confirm? Was just able to reproduce #2 so I'm working on that at the moment.

**Comment by Claymont** [comment]
Can confirm that the menuseparators are the correct thickness on both light and dark now.
