### ISSUE TITLE
Indentation of some menu entries are wrong when using display scaling.

### ISSUE THREAD

**Issue by Claymont** [M1ch431/FirefoxW10ContextMenus#2]
When using Windows display scaling the menu entries like screenshot are indented further than other menu entries.

Below image is taken at 150% display scaling. *I see this at 125% as well.*

![context](https://user-images.githubusercontent.com/28518684/67634668-50d3a380-f8bf-11e9-96ed-0b001f3d4ef9.png)

With 100% display scaling the menus render correctly.

Firefox: 70.0 64-bit & Nightly 64-Bit
OS: Windows 10 64-bit 1903 18362.418
Resolution: 1920x1080p (native)

**Comment by M1ch431** [comment]
Thanks for the reports! Will look into both issues and push out a fix.

**Comment by M1ch431** [comment]
@Claymont https://github.com/M1ch431/FirefoxW10ContextMenus/blob/scaled/userChrome.css
Use that until I can implement a proper fix. It works for 125% and 150%. Assuming 175% works too.

Scaling seems to mess with the padding/spacing of .menu-iconic-text following a context menu icon, checkbox, or radio item.

Just to reiterate this doesn't work for 100% scale, but I believe if I equalize the x values of all menu texts, and add ::before elements which pad the texts and icons I can fix this.

EDIT: It would seem that I messed up the back, forward, reload, bookmark icons slightly in the scaled branch (you probably won't notice it until you read this). Don't worry next commit will fix these things.
