### ISSUE TITLE
Context menu is transparent after latest FF update

### ISSUE THREAD

**Issue by aarivex** [M1ch431/FirefoxW10ContextMenus#3]
After the latest firefox updates, the context menu went completely transparent, making the context menu unreadable at most occasions.

**Examples from Firefox Developer Edition 72.0b2**

![firefox_ewmlKf1giM](https://user-images.githubusercontent.com/18628875/70181860-fa8a2980-16e2-11ea-8dcb-4eff44c76cfb.png)
![firefox_WDcjMfsQag](https://user-images.githubusercontent.com/18628875/70181864-fcec8380-16e2-11ea-98d8-94b0edb0a88d.png)
![firefox_idbkmsIg5x](https://user-images.githubusercontent.com/18628875/70181869-fe1db080-16e2-11ea-9ae8-fa86508b7b02.png)

**Comment by M1ch431** [comment]
Sorry for the late response. I assume this is a Firefox bug, but on my end I fixed it by toggling the dark and light modes in the Settings application while Firefox is open.
I use this on Firefox Nightly and no updates so far have broken it (they are usually only transparent for me when I try this out with a fresh installation of Windows and a fresh profile of Firefox).

Some people report that not working, so you can do this in the meantime (assuming you want the dark theme):
Remove the @media (prefers-color-scheme: light) section (all lines 16-27), and delete line 3 and its brackets (line 4 and 14).

**Comment by rivke41levp656** [comment]
Neither of those seemed to work for me, broke with FF72.

**Comment by hsusanoo** [comment]
Commenting the `@namespace` line will solve the issue.
