### ISSUE TITLE
Menus are transparent FF 72.0.1

### ISSUE THREAD

**Issue by draema** [M1ch431/FirefoxW10ContextMenus#4]
The context menus have transparent backgrounds now in FF 72.0.1.

Highlighting over an option in the menu is not visible
![2020-01-11 19_25_58-Clipboard](https://user-images.githubusercontent.com/25197151/72209659-5ac17780-34a8-11ea-8038-3066c435b670.png)

**Comment by M1ch431** [comment]
See #3
